### ISSUE TITLE
Preview time frame code could be 00:00 by default

### ISSUE THREAD

**Issue by luke14free** [bennord/appstore-tools#4]
A good compromise between implementing complex features for the app preview frame, would be to set it to 00:00 by default , so that designers/motion designers can export videos with the poster frame as the first (or first few) frame(s) of the video. WDYT?

**Comment by luke14free** [comment]
Specifically I was trying to do this by changing L624 of api.py to 

`"attributes": {"fileName": file_name, "fileSize": file_size, "previewFrameTimeCode": "00:00"}`

**Comment by bennord** [comment]
(Linking to the docs for reference)
https://developer.apple.com/documentation/appstoreconnectapi/apppreviewcreaterequest/data/attributes

Since the previewFrameTimeCode is optional, I had left it empty for now.  I assumed (perhaps incorrectly?) that the appstore would use a reasonable default value.

My tentative plan was to specify the frameTime in a text file along-side the preview video.

**Comment by bennord** [comment]
If you're using AppPreviews extensively, then you might be able to test it more than I have up until now, so I appreciate any info/feedback to make it more useful :)

**Comment by bennord** [comment]
> Specifically I was trying to do this by changing L624 of api.py to
> 
> `"attributes": {"fileName": file_name, "fileSize": file_size, "previewFrameTimeCode": "00:00"}`

Yeah, next step could be:
- add frameTimeCode as a param (with default value) to both `create_preview` and `update_preview`
- update `publish_previews` to look for the optional config file beside the preview video and load the frameTimeCode from it's contents.

**Comment by luke14free** [comment]
Absolutely. Unfortunately apple picks a random point in the video for the preview by default, so even 00:00 it's quite useful as it makes it deterministic.

**Comment by luke14free** [comment]
Unfortunately it looks like setting this to "00:00" (or any other value) still wont help as apple will simply ignore it 🤔 - investigating the best way to make this work

**Comment by bennord** [comment]
Is it possible to set it via the appstore connect web interface? Is only the api value ignored, or is the feature not available in general?

**Comment by luke14free** [comment]
looks like I managed to make it work by waiting for the status of the upload to be complete, instead of upload_complete. however, I was thinking that having text files might not make a lot of sense for preview frame times (what if you have multiple previews?)

**Comment by bennord** [comment]
> (what if you have multiple previews?)

One settings file per preview.  The name would match the name of the video file, and sit next to it in the previews directory.

**Comment by bennord** [comment]
https://github.com/bennord/appstore-tools/pull/16 has implemented this via a `json` attributes file.
