### ISSUE TITLE
Prevent .DS_Store files from being uploaded

### ISSUE THREAD

**Issue by luke14free** [bennord/appstore-tools#8]
on mac osx you will typically have .DS_Store files automatically generated by finder. It would probably be better to prevent their upload

```      .DS_Store - reserving asset
      /.../sv/previews/IPHONE_65/.DS_Store - uploading chunk (offset: 0, length: 6148)
      .DS_Store - commiting upload
```

**Comment by bennord** [comment]
Hmm, this is a good point.  Probably should have a white/black list of files for the screenshots and previews folders.

**Comment by luke14free** [comment]
yup! although nowadays they are called `allow_list` and `disallow_list` 💀

could be as simple as accepting only:

```
'jpg','jpeg','png','mp4','mov','avi'
```

**Comment by bennord** [comment]
It's easier for maintainability if we allow as broad a range of image/video files as possible, so it's not a list that needs to be updated whenever apple changes the supported types.

**Comment by bennord** [comment]
@luke14free : It's been a while, but recently I came back to this as I was setting up another IOS project.

Not sure if you are still using this tool, but if so, I've added a new flag `--asset-ignore` that should resolve this issue for you now. https://github.com/bennord/appstore-tools/pull/13

Cheers!
